const CardData = [
  {
    id: 1,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1653818572/Trail%20Addek%20Slides/PSX_20191225_171616_mvwgd3.jpg",
    place: "Sandhakphu, Singalila N. Park",
    level: "Moderate",
    time: "4 Days",
    price: "3000",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1654791402/Trail%20Addek%20Slides/PSX_20191225_205212_ssxzdz.jpg",
    place: "Phalut, Singalila National Park",
    level: "Hard",
    time: "7 Days",
    price: "5151",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1653818587/Trail%20Addek%20Slides/PSX_20191225_205952_i1rljc.jpg",
    place: "Lepchakha, Alipurduar",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717977/samples/landscapes/nature-mountains.jpg",
    place: "Sillery Gaon, Pedong",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717970/samples/landscapes/beach-boat.jpg",
    place: "Lepchakha",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717968/samples/landscapes/architecture-signs.jpg",
    place: "Kolakham, Kalimpong",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717963/samples/landscapes/girl-urban-view.jpg",
    place: "Neora Valley, Kalimpong",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717969/samples/people/bicycle.jpg",
    place: "Tinchuley, Takdah",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717966/samples/people/jazz.jpg",
    place: "Rupang Valley, Santalabari",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717965/samples/people/boy-snow-hoodie.jpg",
    place: "Bamunpukhuri, Garidhura",
    level: "Easy",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/fushigina-shinobi/image/upload/v1652717968/samples/landscapes/architecture-signs.jpg",
    place: "Kolakham, Kalimpong",
    level: "Upcoming",
    time: "1 Day",
    price: "2522",
    cart: "View More",
    description:
      "That might've been one of the shortest assignments in the history of Starfleet. The unexpected is our normal routine.",
    cta: "Add To Cart",
  },
];

export default CardData;
